"use client";
import { useEffect, useState } from "react";
import { Header, AppView } from "@/components/Header";
import { SourcePicker } from "@/components/SourcePicker";
import { UploadArea } from "@/components/UploadArea";
import { MultiSourceList } from "@/components/MultiSourceList";
import { PersonalizeButton } from "@/components/PersonalizeButton";
import { PersonalizeSheet } from "@/components/PersonalizeSheet";
import { ModePicker } from "@/components/ModePicker";
import { StrategyChips } from "@/components/StrategyChips";
import { CustomQuestion } from "@/components/CustomQuestion";
import { GenerateButton } from "@/components/GenerateButton";
import { EmptyOutput } from "@/components/EmptyOutput";
import { StudySpace, WorkspaceView } from "@/components/StudySpace";
import { QuizExperience } from "@/components/QuizExperience";
import { CommunityView } from "@/components/CommunityView";
import { HowItWorks } from "@/components/HowItWorks";
import { defaultLearnerProfile, LearnerProfile, StudyMode, StudySource } from "@/lib/study";
import type { StudySpace as StudySpaceType, StudyStrategy } from "@/lib/ai";
import { defaultDemoStreak, DemoStreak, loadProfile, loadStreak, saveProfile, saveStreak } from "@/lib/demoStorage";
const strategyMap: Record<string, StudyStrategy> = { "Explain simply": "simple", "Exam-ready": "exam-ready", "Key concepts": "key-concepts", "Step-by-step": "step-by-step" };
function LearnView({ profile, openPersonalization, personalizationOpen }: { profile: LearnerProfile; openPersonalization: () => void; personalizationOpen: boolean }) {
 const [draft, setDraft] = useState<StudySource>({ type: "document" }); const [sources, setSources] = useState<StudySource[]>([]); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [mode, setMode] = useState<StudyMode>("explain"); const [strategy, setStrategy] = useState("Exam-ready"); const [question, setQuestion] = useState(""); const [space, setSpace] = useState<StudySpaceType | null>(null); const [workspaceView, setWorkspaceView] = useState<WorkspaceView>("overview"); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
 const ready = sources.filter((source) => source.processedDocument); const selected = ready.filter((source) => selectedIds.includes(source.processedDocument!.id)); const addDraft = (next: StudySource) => { setDraft(next); if (next.processingStatus === "ready" && next.processedDocument) { setSources((items) => items.some((item) => item.processedDocument?.id === next.processedDocument!.id) ? items : [...items, next]); setSelectedIds((ids) => ids.includes(next.processedDocument!.id) ? ids : [...ids, next.processedDocument!.id]); } };
 const generate = async () => { if (!selected.length || loading) { setError("Select at least one ready source before generating."); return; } setLoading(true); setError(""); const selectedSources = selected.map((source) => source.processedDocument!); try { const response = await fetch("/api/study/generate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ source: selectedSources[0], sources: selectedSources, mode, strategy: strategyMap[strategy], learnerContext: { level: profile.level, field: profile.field, goal: profile.goal, language: profile.language }, customQuestion: question.trim() || undefined }) }); const body = await response.json(); if (!response.ok || !body?.success) throw new Error(body?.error?.message ?? "Study-space generation failed."); setSpace(body.studySpace); setWorkspaceView(mode === "quiz" ? "quiz" : "overview"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Study-space generation failed."); } finally { setLoading(false); } };
 if (space) return <main className="min-h-screen bg-canvas pb-28 pt-28"><div className="mx-auto max-w-[1180px] px-4 md:px-10">{workspaceView === "quiz" ? <QuizExperience studySpace={space} learnerContext={{ level: profile.level, field: profile.field, goal: profile.goal, language: profile.language }} onBack={() => setWorkspaceView("overview")} /> : <StudySpace studySpace={space} activeView={workspaceView} onViewChange={setWorkspaceView} onBack={() => setSpace(null)} />}</div></main>;
 return <main className="min-h-screen bg-canvas pb-28 pt-28"><div className="mx-auto max-w-3xl px-4 md:px-10"><header className="mb-8 text-center"><h1 className="font-display text-3xl font-bold sm:text-5xl">What do you want<br />to learn today?</h1><p className="mx-auto mt-3 max-w-lg text-sm text-muted">Bring your notes, lecture material, image or topic. StudyBud helps you understand, practice and remember it your own way.</p></header><div className="space-y-6"><section className="rounded-2xl border border-ink bg-white p-5 shadow-tactile"><p className="text-xs font-bold tracking-wider text-muted">WHAT ARE YOU BRINGING?</p><div className="mt-4"><SourcePicker value={draft.type} onChange={(type) => setDraft({ type })} /><div className="mt-4"><UploadArea source={draft} onSourceChange={addDraft} /></div></div><MultiSourceList sources={sources} selectedIds={selectedIds} onToggle={(id) => setSelectedIds((ids) => ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id])} onSelectAll={() => setSelectedIds(ready.map((source) => source.processedDocument!.id))} onClear={() => setSelectedIds([])} onRemove={(id) => { setSources((items) => items.filter((source) => source.processedDocument?.id !== id)); setSelectedIds((ids) => ids.filter((item) => item !== id)); }} onAdd={() => setDraft({ type: "document" })} /><PersonalizeButton onClick={openPersonalization} /><p className="mt-3 text-xs text-muted">{profile.level} · {profile.field} · {profile.goal} · {profile.language}</p></section><ModePicker value={mode} onChange={setMode} /><StrategyChips value={strategy} onChange={setStrategy} /><CustomQuestion value={question} onChange={setQuestion} onSubmit={generate} /><GenerateButton mode={mode} disabled={!selected.length} loading={loading} onClick={generate} />{error ? <p role="alert" className="rounded-xl border border-coral bg-coral/10 p-4 text-sm">{error}</p> : null}{!ready.length ? <EmptyOutput /> : null}</div></div></main>;
}
export default function HomePage() { const [view, setView] = useState<AppView>("learn"); const [profile, setProfile] = useState<LearnerProfile>(defaultLearnerProfile); const [streak, setStreak] = useState<DemoStreak>(defaultDemoStreak); const [open, setOpen] = useState(false); useEffect(() => { setProfile(loadProfile()); const loaded = loadStreak(); setStreak(loaded); saveStreak(loaded); }, []); return <><Header view={view} onNavigate={setView} profile={profile} streak={streak} onEditProfile={() => setOpen(true)} />{view === "learn" ? <LearnView profile={profile} openPersonalization={() => setOpen(true)} personalizationOpen={open} /> : view === "how-it-works" ? <HowItWorks /> : <CommunityView />}<PersonalizeSheet open={open} profile={profile} onSave={(next) => { setProfile(next); saveProfile(next); }} onClose={() => setOpen(false)} /></>; }
