"use client";
import { useEffect } from "react";
import { ChevronRight, Flame, X } from "lucide-react";
import { LearnerProfile } from "@/lib/study";
export function ProfilePopover({ open, profile, onEdit, onClose }: { open: boolean; profile: LearnerProfile; onEdit: () => void; onClose: () => void }) {
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; if (open) window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [open, onClose]);
  if (!open) return null;
  return <section className="absolute right-0 top-12 z-[70] w-72 animate-[rise_.16s_ease-out] rounded-2xl border border-ink bg-white p-4 shadow-tactile" role="dialog" aria-label="StudyBud demo profile"><div className="flex items-center justify-between"><p className="font-display font-bold">StudyBud Profile</p><button type="button" aria-label="Close profile" onClick={onClose} className="rounded-full p-1 hover:bg-[#eeeeee]"><X size={16} /></button></div><p className="mt-1 text-xs font-semibold uppercase tracking-wider text-muted">Demo profile</p><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between gap-3"><dt className="text-muted">Name</dt><dd className="font-semibold">Student</dd></div><div className="flex justify-between gap-3"><dt className="text-muted">Learning level</dt><dd className="text-right font-semibold">{profile.level}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted">Current goal</dt><dd className="text-right font-semibold">{profile.goal}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted">Language</dt><dd className="font-semibold">{profile.language}</dd></div></dl><div className="mt-4 flex items-center gap-2 rounded-xl border border-ink/20 bg-yellow/25 px-3 py-2 text-sm font-semibold"><Flame size={16} fill="currentColor" />5 day streak</div><button type="button" onClick={onEdit} className="mt-4 flex w-full items-center justify-between rounded-full border border-ink px-3 py-2 font-display text-sm font-semibold hover:bg-[#eeeeee]">Edit preferences <ChevronRight size={16} /></button><button type="button" className="mt-2 w-full rounded-full bg-[#eeeeee] px-3 py-2 font-display text-sm font-semibold text-muted">Continue as guest</button><p className="mt-2 text-center text-[10px] font-semibold uppercase tracking-wider text-muted">Sign in — coming soon</p></section>;
}
