"use client";
import { ArrowLeft } from "lucide-react";
import type { StudySpace as StudySpaceType } from "@/lib/ai";
import { StudyBlockRenderer } from "@/components/study/StudyBlockRenderer";
import { AskBud } from "@/components/study/AskBud";
export type WorkspaceView = "overview" | "learn" | "concepts" | "takeaways" | "quiz" | "ask";
export function StudySpace({ studySpace, activeView = "overview", onViewChange = () => undefined, onBack = () => undefined }: { studySpace: StudySpaceType; activeView?: WorkspaceView; onViewChange?: (view: WorkspaceView) => void; onBack?: () => void }) {
 const nav: WorkspaceView[] = ["overview", "learn", "concepts", "takeaways", "quiz", "ask"];
 const overview = <div className="space-y-5"><section className="rounded-2xl border border-ink bg-[#fffdf5] p-6"><p className="text-xs font-bold tracking-widest">SESSION OVERVIEW</p><p className="mt-3 leading-7">{studySpace.overview}</p></section><section className="rounded-2xl border border-ink bg-yellow p-6"><p className="text-xs font-bold tracking-widest">HIGH-YIELD TAKEAWAY</p><p className="mt-3 font-display text-xl font-bold">{studySpace.blocks.find((b) => b.type === "core_takeaway")?.content || studySpace.keyTakeaways[0]}</p></section><div className="flex flex-wrap gap-2">{studySpace.concepts.map((c) => <button key={c.term} onClick={() => onViewChange("learn")} className="rounded-full border border-ink bg-white px-3 py-2 text-sm">{c.term}</button>)}</div></div>;
 const concepts = <div className="grid gap-3 sm:grid-cols-2">{studySpace.concepts.map((c) => <article key={c.term} className="rounded-xl border border-ink bg-purple/10 p-5"><h2 className="font-display text-xl font-bold">{c.term}</h2><p className="mt-2 text-sm">{c.explanation}</p><button onClick={() => onViewChange("learn")} className="mt-3 text-xs font-bold underline">Explore</button></article>)}</div>;
 const takeaways = <section className="rounded-2xl border border-ink bg-lime/30 p-6"><h2 className="font-display text-xl font-bold">Revision sheet</h2><ul className="mt-4 space-y-3">{studySpace.keyTakeaways.map((x) => <li key={x}>• {x}</li>)}</ul></section>;
 const content = activeView === "ask" ? <AskBud studySpace={studySpace} /> : activeView === "learn" ? <StudyBlockRenderer blocks={studySpace.blocks} /> : activeView === "concepts" ? concepts : activeView === "takeaways" ? takeaways : overview;
 return <section className="mx-auto max-w-[1180px] space-y-5"><header className="rounded-2xl border border-ink bg-white p-5 shadow-tactile"><button onClick={onBack} className="flex gap-1 text-sm font-bold"><ArrowLeft size={16} />Back to Workspace</button><div className="mt-4 flex gap-2"><span className="rounded-full bg-yellow px-2 py-1 text-xs font-bold">{studySpace.metadata.mode}</span><span className="rounded-full bg-pink/20 px-2 py-1 text-xs font-bold">{studySpace.metadata.strategy}</span></div><h1 className="mt-3 font-display text-3xl font-bold">{studySpace.title}</h1><p className="text-sm text-muted">{studySpace.source.fileName}</p></header><nav className="flex gap-2 overflow-x-auto">{nav.map((v) => <button key={v} onClick={() => onViewChange(v)} className={"shrink-0 rounded-full border px-3 py-2 text-xs font-bold " + (activeView === v ? "bg-ink text-white" : "bg-white")}>{v}</button>)}</nav><main>{content}</main></section>;
}
