"use client";
import Image from "next/image";
import { ChangeEvent, DragEvent, useEffect, useRef, useState } from "react";
import { FileImage, FileText, LoaderCircle, Upload, X } from "lucide-react";
import { getSourceFileKind, isSupportedSourceFile, isYouTubeUrl, MAX_IMAGE_SOURCE_FILE_SIZE, MAX_SOURCE_FILE_SIZE, StudySource } from "@/lib/study";
const size = (bytes: number) => bytes < 1048576 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1048576).toFixed(1)} MB`;
export function UploadArea({ source, onSourceChange }: { source: StudySource; onSourceChange: (source: StudySource) => void }) {
 const input = useRef<HTMLInputElement>(null); const [dragging, setDragging] = useState(false); const [error, setError] = useState(""); const [preview, setPreview] = useState<string | null>(null); const file = source.file;
 useEffect(() => { if (!file || source.type !== "image") return setPreview(null); const url = URL.createObjectURL(file); setPreview(url); return () => URL.revokeObjectURL(url); }, [file, source.type]);
 const processDocument = async (candidate: File, kind: string) => { onSourceChange({ type: "document", file: candidate, documentKind: kind, processingStatus: "uploading", processingMessage: "Uploading..." }); try { const form = new FormData(); form.append("file", candidate); const response = await fetch("/api/documents", { method: "POST", body: form }); const raw = await response.text(); let body: { success?: boolean; source?: StudySource["processedDocument"]; error?: { message?: string } } | null = null; try { body = JSON.parse(raw); } catch { throw new Error("Document processing returned an invalid response."); } if (!response.ok || !body?.success || !body.source) throw new Error(body?.error?.message ?? "Document processing failed."); onSourceChange({ type: "document", file: candidate, documentKind: kind, processingStatus: "ready", processingMessage: "Ready to learn", processedDocument: body.source }); } catch (cause) { onSourceChange({ type: "document", file: candidate, documentKind: kind, processingStatus: "error", processingMessage: cause instanceof Error ? cause.message : "Document processing failed." }); } };
 const processImage = async (candidate: File, kind: string) => { onSourceChange({ type: "image", file: candidate, documentKind: kind, processingStatus: "uploading", processingMessage: "Analyzing image..." }); try { const form = new FormData(); form.append("file", candidate); const response = await fetch("/api/images", { method: "POST", body: form }); const body = await response.json(); if (!response.ok || !body?.success || !body.source) throw new Error(body?.error?.message ?? "Image analysis failed."); onSourceChange({ type: "image", file: candidate, documentKind: kind, processingStatus: "ready", processingMessage: "Ready to learn", processedDocument: body.source }); } catch (cause) { onSourceChange({ type: "image", file: candidate, documentKind: kind, processingStatus: "error", processingMessage: cause instanceof Error ? cause.message : "Image analysis failed." }); } }; const select = (candidate?: File) => { if (!candidate) return; const detected = getSourceFileKind(candidate); if (!detected || !isSupportedSourceFile(candidate)) return setError("That file type isn't supported."); const maxBytes = detected.sourceType === "image" ? MAX_IMAGE_SOURCE_FILE_SIZE : MAX_SOURCE_FILE_SIZE; const maxLabel = detected.sourceType === "image" ? "10 MB" : "25 MB"; if (candidate.size > maxBytes) return setError("That file is too large. Max size is " + maxLabel + "."); setError(""); if (detected.sourceType === "document") void processDocument(candidate, detected.label); else void processImage(candidate, detected.label); if (input.current) input.current.value = ""; };
 const drop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); setDragging(false); select(event.dataTransfer.files[0]); };
 if (source.type === "youtube") { const value = source.youtubeUrl ?? ""; const valid = value && isYouTubeUrl(value); return <div className="rounded-xl border border-dashed border-ink bg-[#fffdf5] p-6 text-center"><Upload className="mx-auto mb-3 text-yellow" /><h3 className="font-display text-lg font-semibold">Paste a YouTube link</h3><input value={value} onChange={(e) => onSourceChange({ type: "youtube", youtubeUrl: e.target.value })} className="mt-4 w-full rounded-lg border border-ink bg-white px-4 py-3" placeholder="https://youtube.com/watch?v=..." />{value && <p className={`mt-2 text-xs ${valid ? "text-lime" : "text-coral"}`}>{valid ? "YouTube link looks good." : "Enter a valid YouTube URL."}</p>}</div>; }
 if (source.type === "text") { const value = source.text ?? ""; return <div className="rounded-xl border border-dashed border-ink bg-[#fffdf5] p-6 text-center"><FileText className="mx-auto mb-3 text-yellow" /><h3 className="font-display text-lg font-semibold">Paste your notes</h3><textarea value={value} onChange={(e) => onSourceChange({ type: "text", text: e.target.value })} className="mt-4 w-full rounded-lg border border-ink bg-white px-4 py-3" rows={6} placeholder="Paste notes or a topic..." /><p className="mt-2 text-right text-xs text-muted">{value.length} characters</p></div>; }
 const document = source.type === "document"; const busy = source.processingStatus === "uploading" || source.processingStatus === "extracting";
 return <><div onDragOver={(e) => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={drop} className={`flex min-h-56 flex-col items-center justify-center rounded-xl border border-dashed p-6 text-center transition ${dragging ? "border-2 border-ink bg-yellow/20" : "border-ink bg-[#fffdf5]"}`}><div className={`mb-3 grid h-14 w-14 place-items-center rounded-2xl border border-ink bg-white shadow-tactile ${dragging ? "-translate-y-1" : ""}`}><Upload size={25} /></div><h3 className="font-display text-lg font-semibold">{dragging ? "Drop it here" : document ? "Drop your study material here" : "Drop a diagram or image here"}</h3><p className="mt-1 text-sm text-muted">{document ? "PDF, Word, PowerPoint or Excel · up to 25MB" : "JPG, PNG or WEBP · up to 25MB"}</p><button type="button" onClick={() => input.current?.click()} className="tactile mt-4 rounded-full border border-ink bg-white px-5 py-2 font-display text-sm font-semibold shadow-tactile-sm">[ Browse files ]</button><input ref={input} type="file" accept={document ? ".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt,.md" : ".png,.jpg,.jpeg,.webp"} className="hidden" onChange={(e: ChangeEvent<HTMLInputElement>) => select(e.target.files?.[0])} /></div>{error && <p role="alert" className="mt-2 text-sm font-semibold text-coral">{error}</p>}{file && <div className="mt-4 flex animate-[rise_.22s_ease-out] items-center justify-between rounded-xl border border-ink bg-[#f3f3f3] px-4 py-3"><div className="flex min-w-0 items-center gap-3">{preview ? <Image src={preview} alt="Selected image preview" width={40} height={40} unoptimized className="h-10 w-10 rounded-lg border border-ink object-cover" /> : document ? <FileText size={20} /> : <FileImage size={20} />}<div className="min-w-0"><p className="truncate font-display text-sm font-semibold">{file.name}</p><p className={`text-xs ${source.processingStatus === "error" ? "text-coral" : "text-muted"}`}>{document ? `${source.documentKind} · ` : ""}{size(file.size)} · {busy ? <><LoaderCircle className="mr-1 inline animate-spin" size={12} />{source.processingMessage}</> : source.processingMessage ?? "Ready to learn"}</p></div></div>{source.processingStatus === "error" ? <button onClick={() => file && (document ? void processDocument(file, source.documentKind ?? "Document") : void processImage(file, source.documentKind ?? "Image"))} className="rounded-full border border-ink bg-white px-3 py-1.5 text-xs font-bold">Retry</button> : null}<button aria-label="Remove attached file" onClick={() => onSourceChange({ type: source.type })} className="tactile rounded-full p-2 hover:bg-white"><X size={17} /></button></div>}</>;
}
