"use client";
import { FormEvent, KeyboardEvent, useState } from "react";
import { LoaderCircle, Send, Sparkles } from "lucide-react";
import type { StudySpace } from "@/lib/ai";

type Message = { role: "user" | "assistant"; content: string; references?: Array<{ sourceName: string; reference: { unitType: string; unitNumber: number; label?: string } }> };
export function AskBud({ studySpace }: { studySpace: StudySpace }) {
  const [question, setQuestion] = useState(""); const [messages, setMessages] = useState<Message[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const ask = async (event?: FormEvent, preset?: string) => { event?.preventDefault(); const text = (preset ?? question).trim(); const sources = studySpace.source.normalizedSources ?? (studySpace.source.normalizedSource ? [studySpace.source.normalizedSource] : []); if (!text || loading) return; if (!sources.length) { setError("The original source is not available in this session. Generate the study space again before asking Bud."); return; } setLoading(true); setError(""); setMessages((items) => [...items, { role: "user", content: text }]); setQuestion(""); try { const response = await fetch("/api/study/ask", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ question: text, sources, studyTitle: studySpace.title, history: messages.map(({ role, content }) => ({ role, content })) }) }); const body = await response.json().catch(() => null); if (!response.ok || !body?.success) throw new Error(body?.error?.message ?? "StudyBud couldn't answer that question."); setMessages((items) => [...items, { role: "assistant", content: body.answer, references: body.references }]); } catch (cause) { setError(cause instanceof Error ? cause.message : "StudyBud couldn't answer that question."); } finally { setLoading(false); } };
  const keyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void ask(); } };
  return <section className="rounded-2xl border border-ink bg-white p-5 shadow-tactile"><div className="flex items-center gap-2"><Sparkles size={18} /><h2 className="font-display text-lg font-bold">Ask Bud</h2></div><p className="mt-1 text-sm text-muted">Ask about the source in this study session.</p><div className="mt-4 space-y-3">{messages.length ? messages.map((message, index) => <article key={index} className={"rounded-xl p-3 text-sm " + (message.role === "user" ? "bg-[#f3f3f3]" : "border border-purple/30 bg-purple/10")}><p className="mb-1 text-[10px] font-bold uppercase tracking-wider">{message.role === "user" ? "You" : "Bud"}</p><p className="whitespace-pre-wrap leading-6">{message.content}</p>{message.references?.length ? <p className="mt-2 text-[10px] font-bold text-muted">{message.references.map((ref) => ref.sourceName + " · " + ref.reference.unitType + " " + ref.reference.unitNumber).join(" · ")}</p> : null}</article>) : <p className="rounded-xl bg-[#fffdf5] p-3 text-sm text-muted">Try “Explain this more simply” or “What should I remember for my exam?”</p>}{loading ? <p className="flex items-center gap-2 text-sm font-semibold"><LoaderCircle className="animate-spin" size={16} />Bud is reading your material…</p> : null}</div>{error ? <div className="mt-3 rounded-xl border border-coral bg-coral/10 p-3 text-sm"><p>{error}</p><button onClick={() => void ask(undefined, messages.filter((message) => message.role === "user").at(-1)?.content)} className="mt-2 font-bold underline">Retry</button></div> : null}<div className="mt-4 flex flex-wrap gap-2">{["Explain simpler", "Give an example", "Compare concepts", "Exam tip", "Quiz me"].map((preset) => <button key={preset} disabled={loading} onClick={() => void ask(undefined, preset)} className="rounded-full border border-ink/30 bg-[#fffdf5] px-3 py-1.5 text-xs font-bold disabled:opacity-40">{preset}</button>)}</div><form onSubmit={ask} className="mt-4 flex gap-2"><textarea value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={keyDown} rows={2} placeholder="Ask anything about this material…" className="min-w-0 flex-1 rounded-xl border border-ink bg-white p-3 text-sm outline-none focus:ring-2 focus:ring-purple" /><button disabled={!question.trim() || loading} aria-label="Send question to Ask Bud" className="rounded-xl border border-ink bg-ink px-4 text-white disabled:opacity-40"><Send size={18} /></button></form></section>;
}
